# Generated by Django 2.1.7 on 2019-06-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheckHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=36)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('check_data', models.DateTimeField()),
                ('check_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_uuid', models.CharField(max_length=36, verbose_name='Чек')),
                ('pos_uuid', models.CharField(max_length=36, verbose_name='Позиция')),
                ('product_uuid', models.CharField(max_length=36)),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('check_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acur_research.CheckHead')),
            ],
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название контрагента')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_poll', models.CharField(max_length=255)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('active', models.BooleanField(default=False)),
                ('count_poll', models.IntegerField(default=0, verbose_name='Количетво прохождений')),
                ('work_poll', models.IntegerField(blank=True, default=0, verbose_name='Осталось')),
                ('contr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acur_research.Contragent')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acur_research.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=36, verbose_name='Устройство')),
                ('contr_id', models.IntegerField()),
                ('poll_id', models.IntegerField(verbose_name='Опрос')),
                ('question_id', models.IntegerField(verbose_name='Вопрос')),
                ('answer_id', models.IntegerField(verbose_name='Ответ')),
                ('answer_id_list', models.CharField(max_length=1000, verbose_name='Ответы')),
                ('result_date', models.DateTimeField(verbose_name='Дата и время ответа')),
                ('check_uuid', models.CharField(max_length=36, verbose_name='Чек')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=36, null=True, verbose_name='ID Устройства')),
                ('check_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Номер чека')),
                ('file_obj', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='questionresult',
            index_together={('device_id', 'poll_id', 'question_id', 'answer_id', 'answer_id_list')},
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acur_research.Question', verbose_name='Вопрос'),
        ),
    ]
